\set ON_ERROR_STOP on

-- Fixture sintetica para validar a migration em um Postgres 17 descartavel.
-- Nao deve ser executada no projeto Supabase real.

create role anon nologin;
create role authenticated nologin;
create role service_role nologin bypassrls;

create schema auth;

create table auth.users (
  id uuid primary key
);

create table auth.sessions (
  id uuid primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create or replace function auth.uid()
returns uuid
language sql
stable
as $function$
  select nullif(current_setting('request.jwt.claim.sub', true), '')::uuid;
$function$;

create or replace function auth.jwt()
returns jsonb
language sql
stable
as $function$
  select coalesce(
    nullif(current_setting('request.jwt.claims', true), ''),
    '{}'
  )::jsonb;
$function$;

grant usage on schema auth to anon, authenticated, service_role;
grant execute on function auth.uid(), auth.jwt()
  to anon, authenticated, service_role;

-- Inventario legado confirmado: tabelas vazias, policies permissivas e helpers
-- SECURITY DEFINER com search_path amplo.
create table public.clinics (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  city text,
  created_by uuid not null references auth.users(id),
  created_at timestamptz not null default now()
);

create table public.clinic_members (
  clinic_id uuid not null references public.clinics(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null check (
    role in ('owner', 'professional', 'assistant', 'viewer')
  ),
  status text not null default 'active' check (
    status in ('active', 'suspended')
  ),
  created_at timestamptz not null default now(),
  primary key (clinic_id, user_id)
);

create table public.clinic_audit_log (
  id bigint generated by default as identity primary key,
  clinic_id uuid not null references public.clinics(id) on delete cascade,
  actor uuid references auth.users(id),
  entity text not null,
  entity_id uuid,
  action text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create schema private;

create function private.is_clinic_member(target_clinic uuid)
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $function$
  select exists (
    select 1 from clinic_members
    where clinic_id = target_clinic
      and user_id = auth.uid()
      and status = 'active'
  );
$function$;

create function private.can_write_clinic(target_clinic uuid)
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $function$
  select exists (
    select 1 from clinic_members
    where clinic_id = target_clinic
      and user_id = auth.uid()
      and role in ('owner', 'professional', 'assistant')
      and status = 'active'
  );
$function$;

alter table public.clinics enable row level security;
alter table public.clinic_members enable row level security;
alter table public.clinic_audit_log enable row level security;

grant all on public.clinics, public.clinic_members, public.clinic_audit_log
  to authenticated;
grant usage, select on sequence public.clinic_audit_log_id_seq
  to authenticated;

create policy legacy_clinics_update_owner_without_check
on public.clinics
for update
to authenticated
using (private.can_write_clinic(id));

create policy legacy_members_update_owner_without_check
on public.clinic_members
for update
to authenticated
using (private.can_write_clinic(clinic_id));

create policy legacy_audit_insert_member
on public.clinic_audit_log
for insert
to authenticated
with check (private.is_clinic_member(clinic_id));

create policy legacy_audit_select_member
on public.clinic_audit_log
for select
to authenticated
using (private.is_clinic_member(clinic_id));
