-- Preparacao local da transicao para Supabase Auth + MFA + RBAC.
--
-- Esta migration e deliberadamente aditiva e nao cria usuarios, clinicas ou
-- memberships. O bootstrap das duas contas owner deve ser uma operacao
-- posterior, autenticada e auditada. Ela tambem nao altera as tabelas clinicas
-- legadas, que continuam acessiveis somente pelo service_role/Edge Functions.

create schema if not exists private;

revoke all on schema private from public, anon, authenticated, service_role;

-- Captura no historico local as tres tabelas RBAC que ja existem no projeto
-- remoto. Os IF NOT EXISTS tornam a migration executavel tanto sobre o banco
-- atual quanto sobre um banco local reconstruido do zero.
create table if not exists public.clinics (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  city text,
  created_by uuid not null references auth.users(id) on delete restrict,
  created_at timestamptz not null default now()
);

create table if not exists public.clinic_members (
  clinic_id uuid not null references public.clinics(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null,
  status text not null default 'active',
  created_at timestamptz not null default now(),
  primary key (clinic_id, user_id)
);

create table if not exists public.clinic_audit_log (
  id bigint generated by default as identity primary key,
  clinic_id uuid not null references public.clinics(id) on delete cascade,
  actor uuid references auth.users(id) on delete set null,
  entity text not null,
  entity_id uuid,
  action text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.clinics
  add column if not exists slug text;

alter table public.clinic_members
  add column if not exists display_name text;

alter table public.clinic_audit_log
  add column if not exists actor_role text,
  add column if not exists auth_method text,
  add column if not exists outcome text,
  add column if not exists request_id uuid;

-- Backfills tecnicos apenas para tolerar eventual drift com linhas antigas.
-- No banco inventariado estas tabelas estao vazias.
update public.clinics
set slug = 'clinic-' || replace(id::text, '-', '')
where slug is null;

update public.clinic_members
set display_name = 'Membro ' || left(user_id::text, 8)
where display_name is null;

update public.clinic_audit_log
set actor_role = coalesce(actor_role, 'legacy'),
    auth_method = coalesce(auth_method, 'legacy_shared_secret'),
    outcome = coalesce(outcome, 'success'),
    request_id = coalesce(request_id, gen_random_uuid()),
    entity = coalesce(nullif(btrim(entity), ''), 'legacy'),
    action = coalesce(nullif(btrim(action), ''), 'legacy.unknown'),
    details = coalesce(details, '{}'::jsonb),
    created_at = coalesce(created_at, now())
where actor_role is null
   or auth_method is null
   or outcome is null
   or request_id is null
   or entity is null
   or btrim(entity) = ''
   or action is null
   or btrim(action) = ''
   or details is null
   or created_at is null;

alter table public.clinics
  alter column slug set not null;

alter table public.clinic_members
  alter column display_name set not null;

alter table public.clinic_audit_log
  alter column actor_role set not null,
  alter column auth_method set not null,
  alter column outcome set not null,
  alter column request_id set not null,
  alter column request_id set default gen_random_uuid(),
  alter column entity set not null,
  alter column action set not null,
  alter column details set default '{}'::jsonb,
  alter column details set not null,
  alter column created_at set default now(),
  alter column created_at set not null;

-- Detalhes de auditoria aceitam somente metadados tecnicos pequenos e planos.
-- Nome, CPF, telefone, email, texto clinico, IP, token e payload nao pertencem
-- a esta coluna. Identificadores de recursos ficam nas colunas tipadas.
create or replace function private.audit_details_are_safe(p_details jsonb)
returns boolean
language sql
immutable
strict
parallel safe
set search_path = ''
as $function$
  select jsonb_typeof(p_details) = 'object'
    and pg_column_size(p_details) <= 4096
    and not exists (
      select 1
      from jsonb_each(p_details) as item(key, value)
      where item.key not in (
        'source',
        'mode',
        'route',
        'endpoint',
        'operation',
        'target_kind',
        'reason_code',
        'error_code',
        'http_status',
        'status_code',
        'item_count',
        'result_count',
        'duration_ms',
        'idempotent',
        'version',
        'previous_status',
        'new_status',
        'previous_role',
        'new_role',
        'legacy_event_id'
      )
      or jsonb_typeof(item.value) not in ('string', 'number', 'boolean', 'null')
      or (
        jsonb_typeof(item.value) = 'string'
        and (
          length(item.value #>> '{}') > 160
          or (item.value #>> '{}') !~ '^[A-Za-z0-9_.:/-]*$'
        )
      )
    );
$function$;

revoke execute on function private.audit_details_are_safe(jsonb)
  from public, anon, authenticated, service_role;
grant execute on function private.audit_details_are_safe(jsonb)
  to service_role;

do $migration$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.clinics'::regclass
      and conname = 'clinics_slug_check'
  ) then
    alter table public.clinics
      add constraint clinics_slug_check
      check (
        char_length(slug) between 3 and 80
        and slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'
      );
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.clinics'::regclass
      and conname = 'clinics_slug_key'
  ) then
    alter table public.clinics
      add constraint clinics_slug_key unique (slug);
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.clinics'::regclass
      and conname = 'clinics_name_check'
  ) then
    alter table public.clinics
      add constraint clinics_name_check
      check (char_length(btrim(name)) between 2 and 160);
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.clinics'::regclass
      and conname = 'clinics_city_check'
  ) then
    alter table public.clinics
      add constraint clinics_city_check
      check (city is null or char_length(btrim(city)) between 2 and 120);
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.clinic_members'::regclass
      and conname = 'clinic_members_role_check_v2'
  ) then
    alter table public.clinic_members
      add constraint clinic_members_role_check_v2
      check (role in ('owner', 'professional', 'assistant', 'viewer'));
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.clinic_members'::regclass
      and conname = 'clinic_members_status_check_v2'
  ) then
    alter table public.clinic_members
      add constraint clinic_members_status_check_v2
      check (status in ('active', 'suspended'));
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.clinic_members'::regclass
      and conname = 'clinic_members_display_name_check'
  ) then
    alter table public.clinic_members
      add constraint clinic_members_display_name_check
      check (char_length(btrim(display_name)) between 2 and 120);
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.clinic_audit_log'::regclass
      and conname = 'clinic_audit_log_actor_role_check'
  ) then
    alter table public.clinic_audit_log
      add constraint clinic_audit_log_actor_role_check
      check (actor_role in (
        'owner', 'professional', 'assistant', 'viewer',
        'system', 'legacy', 'unknown'
      ));
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.clinic_audit_log'::regclass
      and conname = 'clinic_audit_log_auth_method_check'
  ) then
    alter table public.clinic_audit_log
      add constraint clinic_audit_log_auth_method_check
      check (auth_method in (
        'supabase_auth', 'legacy_shared_secret', 'service_role', 'system'
      ));
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.clinic_audit_log'::regclass
      and conname = 'clinic_audit_log_outcome_check'
  ) then
    alter table public.clinic_audit_log
      add constraint clinic_audit_log_outcome_check
      check (outcome in ('success', 'denied', 'error'));
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.clinic_audit_log'::regclass
      and conname = 'clinic_audit_log_entity_check'
  ) then
    alter table public.clinic_audit_log
      add constraint clinic_audit_log_entity_check
      check (
        char_length(entity) between 2 and 80
        and entity ~ '^[a-z0-9_.:-]+$'
      );
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.clinic_audit_log'::regclass
      and conname = 'clinic_audit_log_action_check'
  ) then
    alter table public.clinic_audit_log
      add constraint clinic_audit_log_action_check
      check (
        char_length(action) between 2 and 100
        and action ~ '^[a-z0-9_.:-]+$'
      );
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.clinic_audit_log'::regclass
      and conname = 'clinic_audit_log_details_safe_check'
  ) then
    alter table public.clinic_audit_log
      add constraint clinic_audit_log_details_safe_check
      check (private.audit_details_are_safe(details));
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.clinic_audit_log'::regclass
      and conname = 'clinic_audit_log_request_key'
  ) then
    alter table public.clinic_audit_log
      add constraint clinic_audit_log_request_key
      unique (clinic_id, request_id);
  end if;
end
$migration$;

create index if not exists clinics_created_by_idx
  on public.clinics (created_by);

create index if not exists clinic_members_user_status_clinic_idx
  on public.clinic_members (user_id, status, clinic_id);

create index if not exists clinic_members_clinic_role_status_idx
  on public.clinic_members (clinic_id, role, status);

create index if not exists clinic_audit_log_clinic_created_idx
  on public.clinic_audit_log (clinic_id, created_at desc, id desc);

create index if not exists clinic_audit_log_actor_created_idx
  on public.clinic_audit_log (actor, created_at desc)
  where actor is not null;

comment on column public.clinics.slug is
  'Identificador tecnico estavel da clinica; nao contem dado de paciente.';
comment on column public.clinic_members.display_name is
  'Nome operacional para a interface; nunca participa de autorizacao.';
comment on table public.clinic_audit_log is
  'Trilha append-only, sem PHI, gravada somente no servidor/service_role.';
comment on column public.clinic_audit_log.details is
  'Metadados tecnicos em lista permitida; nunca nome, CPF, telefone, email, IP, token ou payload.';
comment on column public.clinic_audit_log.actor_role is
  'Snapshot da funcao RBAC no instante do evento.';
comment on column public.clinic_audit_log.auth_method is
  'supabase_auth, legacy_shared_secret, service_role ou system.';
comment on column public.clinic_audit_log.request_id is
  'UUID de correlacao tecnica; nao reutilizar como identificador de paciente.';

-- Helpers RLS ficam em schema nao exposto, usam o usuario autenticado da
-- propria sessao e nao aceitam user_id fornecido pelo cliente.
create or replace function private.has_aal2()
returns boolean
language sql
stable
security invoker
set search_path = ''
as $function$
  select coalesce((select auth.jwt() ->> 'aal') = 'aal2', false);
$function$;

create or replace function private.is_clinic_member(target_clinic uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $function$
  select (select auth.uid()) is not null
    and exists (
      select 1
      from public.clinic_members as member
      where member.clinic_id = target_clinic
        and member.user_id = (select auth.uid())
        and member.status = 'active'
    );
$function$;

create or replace function private.is_clinic_owner(p_clinic_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $function$
  select (select auth.uid()) is not null
    and exists (
      select 1
      from public.clinic_members as member
      where member.clinic_id = p_clinic_id
        and member.user_id = (select auth.uid())
        and member.role = 'owner'
        and member.status = 'active'
    );
$function$;

create or replace function private.can_write_clinic(target_clinic uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $function$
  select (select auth.uid()) is not null
    and exists (
      select 1
      from public.clinic_members as member
      where member.clinic_id = target_clinic
        and member.user_id = (select auth.uid())
        and member.role in ('owner', 'professional', 'assistant')
        and member.status = 'active'
    );
$function$;

revoke execute on function private.has_aal2()
  from public, anon, authenticated, service_role;
revoke execute on function private.is_clinic_member(uuid)
  from public, anon, authenticated, service_role;
revoke execute on function private.is_clinic_owner(uuid)
  from public, anon, authenticated, service_role;
revoke execute on function private.can_write_clinic(uuid)
  from public, anon, authenticated, service_role;

-- O executor da query precisa de EXECUTE para avaliar uma funcao referenciada
-- por RLS. O schema private continua sem USAGE para clientes, e cada helper
-- devolve apenas boolean calculado a partir de auth.uid() da propria sessao.
grant execute on function private.has_aal2()
  to authenticated;
grant execute on function private.is_clinic_member(uuid)
  to authenticated;
grant execute on function private.is_clinic_owner(uuid)
  to authenticated;
grant execute on function private.can_write_clinic(uuid)
  to authenticated;

-- RPC exclusivamente server-side. A Edge Function primeiro valida o Bearer em
-- /auth/v1/user e depois confirma que o session_id do JWT ainda existe. Logout
-- remove a sessao; expiracao normal continua sendo verificada pelo JWT/Auth.
create or replace function public.clinic_validate_auth_session(
  p_user_id uuid,
  p_session_id uuid
)
returns boolean
language sql
stable
security definer
set search_path = ''
as $function$
  select p_user_id is not null
    and p_session_id is not null
    and exists (
      select 1
      from auth.sessions as session
      where session.id = p_session_id
        and session.user_id = p_user_id
    );
$function$;

comment on function public.clinic_validate_auth_session(uuid, uuid) is
  'Valida server-side se session_id ainda pertence ao usuario; nao substitui /auth/v1/user nem a verificacao de exp.';

revoke all on function public.clinic_validate_auth_session(uuid, uuid)
  from public, anon, authenticated;
grant execute on function public.clinic_validate_auth_session(uuid, uuid)
  to service_role;

-- Nao permite remover ou suspender o ultimo owner ativo. O lock na clinica
-- serializa duas tentativas concorrentes de rebaixamento.
create or replace function private.protect_last_active_clinic_owner()
returns trigger
language plpgsql
security definer
set search_path = ''
as $function$
declare
  remaining_owners integer;
begin
  if old.role = 'owner'
     and old.status = 'active'
     and (
       tg_op = 'DELETE'
       or new.role <> 'owner'
       or new.status <> 'active'
       or new.clinic_id <> old.clinic_id
     ) then
    perform 1
    from public.clinics
    where id = old.clinic_id
    for update;

    select count(*)
    into remaining_owners
    from public.clinic_members as member
    where member.clinic_id = old.clinic_id
      and member.role = 'owner'
      and member.status = 'active'
      and (member.clinic_id, member.user_id) <>
          (old.clinic_id, old.user_id);

    if remaining_owners = 0 then
      raise exception 'a clinica deve manter ao menos um owner ativo'
        using errcode = '23514';
    end if;
  end if;

  if tg_op = 'DELETE' then
    return old;
  end if;
  return new;
end;
$function$;

revoke execute on function private.protect_last_active_clinic_owner()
  from public, anon, authenticated, service_role;

drop trigger if exists clinic_members_protect_last_owner
  on public.clinic_members;
create trigger clinic_members_protect_last_owner
before update or delete on public.clinic_members
for each row execute function private.protect_last_active_clinic_owner();

-- A trilha e imutavel mesmo se um privilegio de UPDATE/DELETE for concedido
-- por engano no futuro.
create or replace function private.reject_clinic_audit_mutation()
returns trigger
language plpgsql
security definer
set search_path = ''
as $function$
begin
  raise exception 'clinic_audit_log e append-only'
    using errcode = '42501';
end;
$function$;

revoke execute on function private.reject_clinic_audit_mutation()
  from public, anon, authenticated, service_role;

drop trigger if exists clinic_audit_log_append_only
  on public.clinic_audit_log;
create trigger clinic_audit_log_append_only
before update or delete on public.clinic_audit_log
for each row execute function private.reject_clinic_audit_mutation();

alter table public.clinics enable row level security;
alter table public.clinic_members enable row level security;
alter table public.clinic_audit_log enable row level security;

-- Remove as policies permissivas antigas (incluindo UPDATE sem WITH CHECK e
-- INSERT direto na auditoria) e recria um conjunto fechado e nominal.
do $migration$
declare
  old_policy record;
begin
  for old_policy in
    select schemaname, tablename, policyname
    from pg_policies
    where schemaname = 'public'
      and tablename in ('clinics', 'clinic_members', 'clinic_audit_log')
  loop
    execute format(
      'drop policy if exists %I on %I.%I',
      old_policy.policyname,
      old_policy.schemaname,
      old_policy.tablename
    );
  end loop;
end
$migration$;

-- Restritiva: nenhuma policy permissiva futura pode contornar o AAL2.
create policy clinics_require_aal2
on public.clinics
as restrictive
for all
to authenticated
using ((select private.has_aal2()))
with check ((select private.has_aal2()));

create policy clinic_members_require_aal2
on public.clinic_members
as restrictive
for all
to authenticated
using ((select private.has_aal2()))
with check ((select private.has_aal2()));

create policy clinic_audit_log_require_aal2
on public.clinic_audit_log
as restrictive
for all
to authenticated
using ((select private.has_aal2()))
with check ((select private.has_aal2()));

create policy clinics_select_active_member
on public.clinics
for select
to authenticated
using ((select private.is_clinic_member(id)));

create policy clinics_update_owner
on public.clinics
for update
to authenticated
using ((select private.is_clinic_owner(id)))
with check ((select private.is_clinic_owner(id)));

create policy clinic_members_select_active_member
on public.clinic_members
for select
to authenticated
using ((select private.is_clinic_member(clinic_id)));

create policy clinic_members_insert_owner
on public.clinic_members
for insert
to authenticated
with check ((select private.is_clinic_owner(clinic_id)));

create policy clinic_members_update_owner
on public.clinic_members
for update
to authenticated
using ((select private.is_clinic_owner(clinic_id)))
with check ((select private.is_clinic_owner(clinic_id)));

create policy clinic_audit_log_select_active_member
on public.clinic_audit_log
for select
to authenticated
using ((select private.is_clinic_member(clinic_id)));

-- Grants explicitos: anon nao alcanca RBAC; authenticated administra somente
-- por colunas seguras + RLS/MFA; service_role faz o bootstrap e as gravacoes
-- server-side sem receber DELETE.
revoke all on table public.clinics
  from public, anon, authenticated, service_role;
revoke all on table public.clinic_members
  from public, anon, authenticated, service_role;
revoke all on table public.clinic_audit_log
  from public, anon, authenticated, service_role;

grant select on table public.clinics to authenticated;
grant update (name, city) on table public.clinics to authenticated;

grant select on table public.clinic_members to authenticated;
grant insert (clinic_id, user_id, role, status, display_name)
  on table public.clinic_members to authenticated;
grant update (role, status, display_name)
  on table public.clinic_members to authenticated;

grant select on table public.clinic_audit_log to authenticated;

grant select, insert, update on table public.clinics to service_role;
grant select, insert, update on table public.clinic_members to service_role;
grant select, insert on table public.clinic_audit_log to service_role;

do $migration$
declare
  audit_sequence regclass;
begin
  audit_sequence := pg_get_serial_sequence(
    'public.clinic_audit_log',
    'id'
  )::regclass;

  if audit_sequence is not null then
    execute format(
      'revoke all on sequence %s from public, anon, authenticated, service_role',
      audit_sequence
    );
    execute format(
      'grant usage, select on sequence %s to service_role',
      audit_sequence
    );
  end if;
end
$migration$;
